name: Run Check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read

concurrency:
  group: pr-test-execution-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  basic-tests:
    name: Basic tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Получить исходный код
        uses: actions/checkout@v4

      - name: Запустить базовые тесты
        run: ./tests/basic.sh
