name: Full tests

on:
  pull_request:
    branches:
      - main
    types:
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  full-tests:
    name: Full tests
    if: github.event.label.name == 'run-full-tests'
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Получить исходный код
        uses: actions/checkout@v4

      - name: Запустить полный набор тестов
        run: ./tests/full.sh
